feat: Automatically install pipx/brew/gpg in make install

diff --git a/{{cookiecutter.project_name}}/makefile b/{{cookiecutter.project_name}}/makefile
--- a/{{cookiecutter.project_name}}/makefile
+++ b/{{cookiecutter.project_name}}/makefile
@@ -26,28 +26,60 @@ export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
 help:
 	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' makefile | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
 
-install-poetry:
-	@if [ ! "$(shell poetry --version)" = "Poetry (version 1.4.0)" ]; then \
-		pip3 install --force --quiet poetry==1.4.0; \
-		echo "Installed Poetry."; \
+install: ## Install dependencies
+	@echo "Installing the '{{ cookiecutter.project_name }}' project..."
+	@$(MAKE) --quiet install-brew
+	@$(MAKE) --quiet install-gpg
+	@$(MAKE) --quiet install-pipx
+	@$(MAKE) --quiet install-poetry
+	@$(MAKE) --quiet setup-poetry
+	@$(MAKE) --quiet setup-environment-variables
+	@$(MAKE) --quiet setup-git
+	@$(MAKE) --quiet add-repo-to-git
+	@echo "Installed the '{{ cookiecutter.project_name }}' project."
+
+install-brew:
+	@if [ $$(uname) == "Darwin" && "$(shell which brew)" = "" ]; then \
+		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"; \
+		echo "Installed Homebrew."; \
 	fi
 
-uninstall-poetry:
-	@echo "Uninstalling poetry..."
-	@pip3 uninstall poetry
-
-install: ## Install dependencies
+install-gpg:
 	@if [ "$(shell which gpg)" = "" ]; then \
-		echo "GPG not installed. Install GPG on MacOS with `brew install gnupg` or "; \
-			 "on Ubuntu with `apt install gnupg` and run `make install` again."; \
-	else \
-		echo "Installing the '{{ cookiecutter.project_name }}' project..."; \
-		$(MAKE) --quiet install-poetry; \
-		$(MAKE) --quiet setup-poetry; \
-		$(MAKE) --quiet setup-environment-variables; \
-		$(MAKE) --quiet setup-git; \
-		$(MAKE) --quiet add-repo-to-git; \
-		echo "Installed the '{{ cookiecutter.project_name }}' project."; \
+		uname=$$(uname); \
+			case $${uname} in \
+				(*Linux*) distro=$$(lsb_release -i | sed 's/Distributor ID:\t//'); \
+					case $${distro} in \
+						(*Ubuntu*) installCmd='apt-get update && apt-get install -y gnupg'; \
+						(*CentOS*) installCmd='yum install -y gnupg'; \
+						(*) echo 'Could not automatically install gnupg for the $${distro} distribution. Please manually install gnupg and try again.'; exit 2; ;; \
+					esac; ;; \
+				(*Darwin*) installCmd='brew install gnupg'; ;; \
+				(*) echo 'Could not automatically install gnupg. Please manually install gnupg and try again.'; exit 2; ;; \
+			esac; \
+			"$${installCmd}"; \
+		echo "Installed gnupg. Now generating a new GPG key - please follow the prompts."; \
+		gpg --full-generate-key; \
+	fi
+
+install-pipx:
+	@if [ "$(shell which pipx)" = "" ]; then \
+		uname=$$(uname); \
+			case $${uname} in \
+				(*Linux*) installCmd='apt-get update && apt-get install -y pipx'; ;; \
+				(*Darwin*) installCmd='brew install pipx'; ;; \
+				(*CYGWIN*) installCmd='py -3 -m pip install --user pipx'; ;; \
+				(*) installCmd='python3 -m pip install --user pipx'; ;; \
+			esac; \
+			"$${installCmd}"; \
+		pipx ensurepath; \
+		echo "Installed pipx."; \
+	fi
+
+install-poetry:
+	@if [ ! "$(shell poetry --version)" = "Poetry (version 1.5.1)" ]; then \
+		pipx install --force --quiet poetry==1.5.1; \
+		echo "Installed Poetry."; \
 	fi
 
 setup-poetry:
