fix: Semicolons

diff --git a/{{cookiecutter.project_name}}/makefile b/{{cookiecutter.project_name}}/makefile
--- a/{{cookiecutter.project_name}}/makefile
+++ b/{{cookiecutter.project_name}}/makefile
@@ -78,12 +78,12 @@ install-gpg:
 			case $${uname} in \
 				(*Linux*) distro=$$(lsb_release -i | sed 's/Distributor ID:\t//'); \
 					case $${distro} in \
-						(*Ubuntu*) installCmd='apt-get update && apt-get install -y gnupg gpg-agent'; \
-						(*CentOS*) installCmd='yum install -y gnupg gpg-agent'; \
-						(*) echo 'Could not automatically install gnupg for the $${distro} distribution. Please manually install gnupg and try again.'; exit 2; \
-					esac; \
-				(*Darwin*) installCmd='brew install gnupg pinentry-mac'; \
-				(*) echo 'Could not automatically install gnupg. Please manually install gnupg and try again.'; exit 2; \
+						(*Ubuntu*) installCmd='apt-get update && apt-get install -y gnupg gpg-agent';; \
+						(*CentOS*) installCmd='yum install -y gnupg gpg-agent';; \
+						(*) echo 'Could not automatically install gnupg for the $${distro} distribution. Please manually install gnupg and try again.'; exit 2;; \
+					esac;; \
+				(*Darwin*) installCmd='brew install gnupg pinentry-mac';; \
+				(*) echo 'Could not automatically install gnupg. Please manually install gnupg and try again.'; exit 2;; \
 			esac; \
 			"$${installCmd}"; \
 		echo "Installed gnupg."; \
@@ -102,9 +102,9 @@ install-pipx:
 	@if [ "$(shell which pipx)" = "" ]; then \
 		uname=$$(uname); \
 			case $${uname} in \
-				(*Darwin*) installCmd='brew install pipx'; \
-				(*CYGWIN*) installCmd='py -3 -m pip install --upgrade --user pipx'; \
-				(*) installCmd='python3 -m pip install --upgrade --user pipx'; \
+				(*Darwin*) installCmd='brew install pipx';; \
+				(*CYGWIN*) installCmd='py -3 -m pip install --upgrade --user pipx';; \
+				(*) installCmd='python3 -m pip install --upgrade --user pipx';; \
 			esac; \
 			$${installCmd}; \
 		pipx ensurepath --force; \
@@ -183,10 +183,10 @@ view-docs:  ## View documentation
 	@echo "Viewing API documentation..."
 	@uname=$$(uname); \
 		case $${uname} in \
-			(*Linux*) openCmd='xdg-open'; \
-			(*Darwin*) openCmd='open'; \
-			(*CYGWIN*) openCmd='cygstart'; \
-			(*) echo 'Error: Unsupported platform: $${uname}'; exit 2; \
+			(*Linux*) openCmd='xdg-open';; \
+			(*Darwin*) openCmd='open';; \
+			(*CYGWIN*) openCmd='cygstart';; \
+			(*) echo 'Error: Unsupported platform: $${uname}'; exit 2;; \
 		esac; \
 		"$${openCmd}" docs/{{ cookiecutter.project_name }}.html
 
